import { Formula } from "@/types";

// Comprehensive Excel Formula Database
export const FORMULAS: Formula[] = [
  // LOOKUP & REFERENCE
  {
    id: "xlookup",
    name: "XLOOKUP",
    category: "lookup",
    syntax: "XLOOKUP(lookup_value, lookup_array, return_array, [if_not_found], [match_mode], [search_mode])",
    description: "Searches a range or array for a match and returns the corresponding item from a second range or array.",
    isModern: true,
    isVolatile: false,
    arguments: [
      { name: "lookup_value", description: "The value to search for", required: true, type: "any" },
      { name: "lookup_array", description: "The array or range to search", required: true, type: "range" },
      { name: "return_array", description: "The array or range to return", required: true, type: "range" },
      { name: "if_not_found", description: "Value to return if no match is found", required: false, type: "any" },
      { name: "match_mode", description: "0=exact, -1=exact or next smaller, 1=exact or next larger, 2=wildcard", required: false, type: "number" },
      { name: "search_mode", description: "1=first to last, -1=last to first, 2=binary ascending, -2=binary descending", required: false, type: "number" },
    ],
    examples: [
      {
        title: "Basic lookup",
        formula: '=XLOOKUP(E2, A2:A10, B2:B10)',
        input: 'Find "Apple" in column A',
        output: 'Returns corresponding value from column B',
        explanation: "Simple lookup that replaces VLOOKUP. Returns #N/A if not found.",
        level: "beginner",
      },
      {
        title: "Lookup with default",
        formula: '=XLOOKUP(E2, A2:A10, B2:B10, "Not Found")',
        input: 'Search with error handling',
        output: 'Returns "Not Found" instead of #N/A',
        explanation: "The fourth parameter provides a custom message when no match exists.",
        level: "intermediate",
      },
      {
        title: "Approximate match",
        formula: '=XLOOKUP(E2, A2:A10, B2:B10, , -1)',
        input: 'Find exact or next smaller value',
        output: 'Returns closest match',
        explanation: "Useful for tiered pricing or grade boundaries. Data doesn't need to be sorted.",
        level: "advanced",
      },
    ],
    pitfalls: [
      "Lookup array and return array must be the same size",
      "Not available in older Excel versions (requires Office 365)",
      "Binary search modes require sorted data",
    ],
    alternatives: ["VLOOKUP", "INDEX/MATCH", "LOOKUP"],
    performanceNotes: "Faster than VLOOKUP for large datasets. Use binary search mode when data is sorted for best performance.",
  },
  {
    id: "vlookup",
    name: "VLOOKUP",
    category: "lookup",
    syntax: "VLOOKUP(lookup_value, table_array, col_index_num, [range_lookup])",
    description: "Searches for a value in the first column of a table and returns a value in the same row from another column.",
    isModern: false,
    isVolatile: false,
    arguments: [
      { name: "lookup_value", description: "The value to search for in the first column", required: true, type: "any" },
      { name: "table_array", description: "The table of information", required: true, type: "range" },
      { name: "col_index_num", description: "The column number in table_array to return", required: true, type: "number" },
      { name: "range_lookup", description: "TRUE=approximate match, FALSE=exact match", required: false, type: "boolean" },
    ],
    examples: [
      {
        title: "Exact match lookup",
        formula: '=VLOOKUP(A2, Products!A:D, 3, FALSE)',
        input: 'Find product ID in column A',
        output: 'Returns price from column 3',
        explanation: "FALSE ensures exact match. Returns #N/A if not found.",
        level: "beginner",
      },
      {
        title: "Approximate match for ranges",
        formula: '=VLOOKUP(B2, TaxTable!A:B, 2, TRUE)',
        input: 'Income value to find tax bracket',
        output: 'Returns tax rate',
        explanation: "TRUE finds the largest value less than or equal to lookup_value. First column must be sorted ascending.",
        level: "intermediate",
      },
      {
        title: "Dynamic column index",
        formula: '=VLOOKUP($A2, Data!$A:$Z, MATCH(B$1, Data!$A$1:$Z$1, 0), FALSE)',
        input: 'Lookup with variable column',
        output: 'Returns value from matched header',
        explanation: "MATCH finds the column number dynamically, making formula more flexible.",
        level: "advanced",
      },
    ],
    pitfalls: [
      "Can only search left to right (lookup column must be leftmost)",
      "Column index is fragile - breaks if columns are inserted",
      "Case-insensitive - treats 'apple' and 'Apple' as the same",
      "With TRUE, data must be sorted or results will be wrong",
    ],
    alternatives: ["XLOOKUP", "INDEX/MATCH"],
    performanceNotes: "Consider XLOOKUP for new workbooks. INDEX/MATCH is more flexible and faster for large datasets.",
  },
  {
    id: "index-match",
    name: "INDEX/MATCH",
    category: "lookup",
    syntax: "INDEX(return_range, MATCH(lookup_value, lookup_range, 0))",
    description: "Powerful combination that finds a value in one range and returns corresponding value from another range.",
    isModern: false,
    isVolatile: false,
    arguments: [
      { name: "return_range", description: "Range containing the values to return", required: true, type: "range" },
      { name: "lookup_value", description: "Value to search for", required: true, type: "any" },
      { name: "lookup_range", description: "Range to search in", required: true, type: "range" },
    ],
    examples: [
      {
        title: "Basic lookup",
        formula: '=INDEX(B2:B10, MATCH(E2, A2:A10, 0))',
        input: 'Find position and return value',
        output: 'Corresponding value from B column',
        explanation: "MATCH finds the row position, INDEX returns the value at that position.",
        level: "beginner",
      },
      {
        title: "Left lookup",
        formula: '=INDEX(A2:A10, MATCH(E2, C2:C10, 0))',
        input: 'Lookup from right column to left',
        output: 'Value from left column',
        explanation: "Unlike VLOOKUP, can return values to the left of lookup column.",
        level: "intermediate",
      },
      {
        title: "Two-way lookup",
        formula: '=INDEX(B2:F10, MATCH(A12, A2:A10, 0), MATCH(B11, B1:F1, 0))',
        input: 'Match both row and column',
        output: 'Value at intersection',
        explanation: "Finds value at the intersection of a specific row and column. Like a dynamic pivot.",
        level: "advanced",
      },
    ],
    pitfalls: [
      "More complex syntax than XLOOKUP",
      "Ranges must be properly aligned",
      "Returns #N/A if not found (wrap in IFERROR if needed)",
    ],
    alternatives: ["XLOOKUP", "VLOOKUP"],
    performanceNotes: "Faster than VLOOKUP for large datasets. More flexible but requires understanding two functions.",
  },
  // TEXT FUNCTIONS
  {
    id: "textsplit",
    name: "TEXTSPLIT",
    category: "text",
    syntax: "TEXTSPLIT(text, col_delimiter, [row_delimiter], [ignore_empty], [match_mode], [pad_with])",
    description: "Splits text into rows or columns using delimiters.",
    isModern: true,
    isVolatile: false,
    arguments: [
      { name: "text", description: "The text to split", required: true, type: "text" },
      { name: "col_delimiter", description: "Character(s) to split by for columns", required: true, type: "text" },
      { name: "row_delimiter", description: "Character(s) to split by for rows", required: false, type: "text" },
      { name: "ignore_empty", description: "TRUE to ignore consecutive delimiters", required: false, type: "boolean" },
      { name: "match_mode", description: "0=case-sensitive, 1=case-insensitive", required: false, type: "number" },
      { name: "pad_with", description: "Value to pad arrays with", required: false, type: "any" },
    ],
    examples: [
      {
        title: "Split full name",
        formula: '=TEXTSPLIT(A2, " ")',
        input: '"John Smith"',
        output: 'John | Smith (in two cells)',
        explanation: "Splits text by space into separate cells horizontally.",
        level: "beginner",
      },
      {
        title: "Split CSV data",
        formula: '=TEXTSPLIT(A2, ",", CHAR(10))',
        input: 'Multi-line CSV text',
        output: 'Array of values',
        explanation: "Splits by comma for columns and line break for rows, creating a 2D array.",
        level: "intermediate",
      },
      {
        title: "Clean split ignoring empties",
        formula: '=TEXTSPLIT(A2, " ", , TRUE)',
        input: '"John  Smith" (extra spaces)',
        output: 'John | Smith',
        explanation: "Ignores multiple consecutive spaces between words.",
        level: "intermediate",
      },
    ],
    pitfalls: [
      "Only available in Excel 365",
      "Spills into multiple cells - ensure space is available",
      "Returns #SPILL! error if result range is blocked",
    ],
    alternatives: ["LEFT/RIGHT/MID", "Text to Columns feature", "Power Query"],
    performanceNotes: "Much faster than using multiple LEFT/RIGHT/FIND combinations. Results spill automatically.",
  },
  {
    id: "textbefore",
    name: "TEXTBEFORE",
    category: "text",
    syntax: "TEXTBEFORE(text, delimiter, [instance_num], [match_mode], [match_end], [if_not_found])",
    description: "Returns text that occurs before a specific character or substring.",
    isModern: true,
    isVolatile: false,
    arguments: [
      { name: "text", description: "The text to search", required: true, type: "text" },
      { name: "delimiter", description: "The character or text to search for", required: true, type: "text" },
      { name: "instance_num", description: "Which occurrence to use (negative = from end)", required: false, type: "number" },
      { name: "match_mode", description: "0=case-sensitive, 1=case-insensitive", required: false, type: "number" },
      { name: "match_end", description: "TRUE=treat end of text as delimiter", required: false, type: "boolean" },
      { name: "if_not_found", description: "Value to return if delimiter not found", required: false, type: "any" },
    ],
    examples: [
      {
        title: "Extract first name",
        formula: '=TEXTBEFORE(A2, " ")',
        input: '"John Smith"',
        output: '"John"',
        explanation: "Returns everything before the first space.",
        level: "beginner",
      },
      {
        title: "Get email username",
        formula: '=TEXTBEFORE(A2, "@")',
        input: '"john@example.com"',
        output: '"john"',
        explanation: "Extracts the part before @ symbol in email addresses.",
        level: "beginner",
      },
      {
        title: "Get file path",
        formula: '=TEXTBEFORE(A2, "/", -1)',
        input: '"/folder/subfolder/file.xlsx"',
        output: '"/folder/subfolder"',
        explanation: "Using -1 gets text before the last occurrence of delimiter.",
        level: "intermediate",
      },
    ],
    pitfalls: [
      "Only available in Excel 365",
      "Returns #N/A if delimiter not found (use if_not_found parameter)",
    ],
    alternatives: ["LEFT/FIND", "TEXTAFTER", "TEXTSPLIT"],
    performanceNotes: "Cleaner and more readable than LEFT/FIND combinations.",
  },
  {
    id: "textafter",
    name: "TEXTAFTER",
    category: "text",
    syntax: "TEXTAFTER(text, delimiter, [instance_num], [match_mode], [match_end], [if_not_found])",
    description: "Returns text that occurs after a specific character or substring.",
    isModern: true,
    isVolatile: false,
    arguments: [
      { name: "text", description: "The text to search", required: true, type: "text" },
      { name: "delimiter", description: "The character or text to search for", required: true, type: "text" },
      { name: "instance_num", description: "Which occurrence to use (negative = from end)", required: false, type: "number" },
      { name: "match_mode", description: "0=case-sensitive, 1=case-insensitive", required: false, type: "number" },
      { name: "match_end", description: "TRUE=treat end of text as delimiter", required: false, type: "boolean" },
      { name: "if_not_found", description: "Value to return if delimiter not found", required: false, type: "any" },
    ],
    examples: [
      {
        title: "Extract last name",
        formula: '=TEXTAFTER(A2, " ")',
        input: '"John Smith"',
        output: '"Smith"',
        explanation: "Returns everything after the first space.",
        level: "beginner",
      },
      {
        title: "Get email domain",
        formula: '=TEXTAFTER(A2, "@")',
        input: '"john@example.com"',
        output: '"example.com"',
        explanation: "Extracts the domain part of email addresses.",
        level: "beginner",
      },
      {
        title: "Extract file extension",
        formula: '=TEXTAFTER(A2, ".", -1)',
        input: '"document.backup.xlsx"',
        output: '"xlsx"',
        explanation: "Using -1 gets text after the last occurrence of the delimiter.",
        level: "intermediate",
      },
    ],
    pitfalls: [
      "Only available in Excel 365",
      "Returns #N/A if delimiter not found (use if_not_found parameter)",
    ],
    alternatives: ["RIGHT/FIND", "TEXTBEFORE", "TEXTSPLIT"],
    performanceNotes: "Much simpler than complex RIGHT/LEN/FIND formulas.",
  },
  // DYNAMIC ARRAY FUNCTIONS
  {
    id: "filter",
    name: "FILTER",
    category: "dynamic-array",
    syntax: "FILTER(array, include, [if_empty])",
    description: "Filters a range of data based on criteria you define.",
    isModern: true,
    isVolatile: false,
    arguments: [
      { name: "array", description: "The range or array to filter", required: true, type: "range" },
      { name: "include", description: "Boolean array where TRUE means include the row", required: true, type: "array" },
      { name: "if_empty", description: "Value to return if no results", required: false, type: "any" },
    ],
    examples: [
      {
        title: "Filter by single condition",
        formula: '=FILTER(A2:D100, C2:C100="Active")',
        input: 'Data with Status column',
        output: 'Only rows where Status is "Active"',
        explanation: "Returns all columns for rows matching the condition. Result spills automatically.",
        level: "beginner",
      },
      {
        title: "Filter with multiple conditions (AND)",
        formula: '=FILTER(A2:D100, (C2:C100="Active") * (D2:D100>1000))',
        input: 'Status="Active" AND Amount>1000',
        output: 'Rows matching both conditions',
        explanation: "Multiply conditions with * for AND logic. Both must be TRUE (1*1=1).",
        level: "intermediate",
      },
      {
        title: "Filter with OR logic",
        formula: '=FILTER(A2:D100, (B2:B100="North")+(B2:B100="South"), "No data")',
        input: 'Region is North OR South',
        output: 'Rows from either region',
        explanation: "Use + for OR logic. Returns \"No data\" if no matches found.",
        level: "advanced",
      },
    ],
    pitfalls: [
      "Only available in Excel 365",
      "Include array must match array dimensions",
      "Returns #CALC! if conditions produce no matches (use if_empty)",
      "Spills - needs empty space below the formula",
    ],
    alternatives: ["Advanced Filter", "Power Query", "Manual filtering"],
    performanceNotes: "Very fast even with large datasets. Updates automatically when source data changes.",
  },
  {
    id: "sort",
    name: "SORT",
    category: "dynamic-array",
    syntax: "SORT(array, [sort_index], [sort_order], [by_col])",
    description: "Sorts the contents of a range or array.",
    isModern: true,
    isVolatile: false,
    arguments: [
      { name: "array", description: "The range or array to sort", required: true, type: "range" },
      { name: "sort_index", description: "Column/row number to sort by", required: false, type: "number" },
      { name: "sort_order", description: "1=ascending, -1=descending", required: false, type: "number" },
      { name: "by_col", description: "FALSE=sort by row (default), TRUE=sort by column", required: false, type: "boolean" },
    ],
    examples: [
      {
        title: "Simple sort",
        formula: '=SORT(A2:D100)',
        input: 'Unsorted data',
        output: 'Data sorted by first column A-Z',
        explanation: "Sorts entire range by first column in ascending order.",
        level: "beginner",
      },
      {
        title: "Sort by specific column descending",
        formula: '=SORT(A2:D100, 3, -1)',
        input: 'Sort by 3rd column (Amount)',
        output: 'Largest to smallest',
        explanation: "Sorts by column 3 in descending order. All columns stay aligned.",
        level: "intermediate",
      },
      {
        title: "Multi-level sort",
        formula: '=SORTBY(A2:D100, B2:B100, 1, C2:C100, -1)',
        input: 'Sort by Region then Amount',
        output: 'Grouped by region, high to low amounts',
        explanation: "Use SORTBY for multiple sort columns. Pairs of range and order.",
        level: "advanced",
      },
    ],
    pitfalls: [
      "Only available in Excel 365",
      "Creates a copy - doesn't sort in place",
      "Text and numbers sorted separately",
    ],
    alternatives: ["Manual sort", "SORTBY for multi-column", "Power Query"],
    performanceNotes: "Fast and dynamic. Updates automatically when source changes.",
  },
  {
    id: "unique",
    name: "UNIQUE",
    category: "dynamic-array",
    syntax: "UNIQUE(array, [by_col], [exactly_once])",
    description: "Returns a list of unique values from a range or array.",
    isModern: true,
    isVolatile: false,
    arguments: [
      { name: "array", description: "The range or array to get unique values from", required: true, type: "range" },
      { name: "by_col", description: "FALSE=compare rows (default), TRUE=compare columns", required: false, type: "boolean" },
      { name: "exactly_once", description: "FALSE=all unique, TRUE=only values that occur once", required: false, type: "boolean" },
    ],
    examples: [
      {
        title: "Get unique list",
        formula: '=UNIQUE(A2:A100)',
        input: 'List with duplicates',
        output: 'Each value once',
        explanation: "Simple unique list, like Remove Duplicates but dynamic.",
        level: "beginner",
      },
      {
        title: "Unique combinations",
        formula: '=UNIQUE(A2:B100)',
        input: 'Two columns (Name, Region)',
        output: 'Unique name-region pairs',
        explanation: "Returns unique combinations across multiple columns.",
        level: "intermediate",
      },
      {
        title: "Values that occur exactly once",
        formula: '=UNIQUE(A2:A100, , TRUE)',
        input: 'List with some duplicates',
        output: 'Only non-repeated values',
        explanation: "Excludes any value that appears more than once. Useful for finding singletons.",
        level: "advanced",
      },
    ],
    pitfalls: [
      "Only available in Excel 365",
      "Case-insensitive - 'Apple' and 'apple' treated as same",
      "Spills down, needs empty space",
    ],
    alternatives: ["Remove Duplicates", "Pivot table", "Power Query"],
    performanceNotes: "Very efficient. Updates live when source data changes.",
  },
  // LOGICAL FUNCTIONS
  {
    id: "ifs",
    name: "IFS",
    category: "logical",
    syntax: "IFS(logical_test1, value_if_true1, [logical_test2, value_if_true2], ...)",
    description: "Checks multiple conditions and returns a value corresponding to the first TRUE condition.",
    isModern: true,
    isVolatile: false,
    arguments: [
      { name: "logical_test1", description: "First condition to check", required: true, type: "boolean" },
      { name: "value_if_true1", description: "Value to return if test1 is TRUE", required: true, type: "any" },
      { name: "logical_test2", description: "Second condition to check", required: false, type: "boolean" },
      { name: "value_if_true2", description: "Value to return if test2 is TRUE", required: false, type: "any" },
    ],
    examples: [
      {
        title: "Grade calculator",
        formula: '=IFS(A2>=90,"A", A2>=80,"B", A2>=70,"C", A2>=60,"D", TRUE,"F")',
        input: 'Score value',
        output: 'Letter grade',
        explanation: "Cleaner than nested IFs. Use TRUE as last condition for default value.",
        level: "beginner",
      },
      {
        title: "Status based on multiple fields",
        formula: '=IFS(B2="", "Not Started", C2>TODAY(), "Overdue", D2="Yes", "Complete", TRUE, "In Progress")',
        input: 'Various field conditions',
        output: 'Status text',
        explanation: "Tests multiple columns. First TRUE condition wins.",
        level: "intermediate",
      },
      {
        title: "Tiered pricing",
        formula: '=IFS(A2>=1000, A2*0.9, A2>=500, A2*0.95, A2>=100, A2*0.98, TRUE, A2)',
        input: 'Order quantity',
        output: 'Price with discount',
        explanation: "Applies different discount tiers. Order matters - checks from top down.",
        level: "intermediate",
      },
    ],
    pitfalls: [
      "Only available in Excel 365 and Excel 2019+",
      "Returns #N/A if no condition is TRUE - always include TRUE as last test for default",
      "Can't be empty - must have at least one test/value pair",
    ],
    alternatives: ["Nested IF", "SWITCH", "CHOOSE"],
    performanceNotes: "Much more readable than nested IFs. Similar performance.",
  },
  {
    id: "switch",
    name: "SWITCH",
    category: "logical",
    syntax: "SWITCH(expression, value1, result1, [value2, result2], ..., [default])",
    description: "Evaluates an expression against a list of values and returns the result corresponding to the first matching value.",
    isModern: true,
    isVolatile: false,
    arguments: [
      { name: "expression", description: "The value to compare", required: true, type: "any" },
      { name: "value1", description: "First value to match against", required: true, type: "any" },
      { name: "result1", description: "Result if expression = value1", required: true, type: "any" },
      { name: "default", description: "Value to return if no match (optional last parameter)", required: false, type: "any" },
    ],
    examples: [
      {
        title: "Day name to number",
        formula: '=SWITCH(A2, "Mon",1, "Tue",2, "Wed",3, "Thu",4, "Fri",5, "Sat",6, "Sun",7, "Invalid")',
        input: '"Wed"',
        output: '3',
        explanation: "Converts day names to numbers. Last value is default if no match.",
        level: "beginner",
      },
      {
        title: "Status code translator",
        formula: '=SWITCH(A2, 200,"OK", 404,"Not Found", 500,"Server Error", "Unknown")',
        input: 'HTTP status code',
        output: 'Human readable status',
        explanation: "Perfect for lookup tables. Cleaner than nested IFs.",
        level: "beginner",
      },
      {
        title: "Complex calculations by category",
        formula: '=SWITCH(A2, "Standard", B2*1.1, "Premium", B2*1.25, "VIP", B2*1.5, B2)',
        input: 'Customer tier',
        output: 'Price with markup',
        explanation: "Different calculations for different cases. Default returns base price.",
        level: "intermediate",
      },
    ],
    pitfalls: [
      "Only available in Excel 365 and Excel 2019+",
      "Only tests for exact equality - can't use > or < conditions",
      "Returns #N/A if no match and no default provided",
    ],
    alternatives: ["IFS", "nested IF", "XLOOKUP with a lookup table"],
    performanceNotes: "Cleaner and slightly faster than nested IFs for exact match scenarios.",
  },
  // MATH & STATISTICAL
  {
    id: "sumifs",
    name: "SUMIFS",
    category: "math",
    syntax: "SUMIFS(sum_range, criteria_range1, criterion1, [criteria_range2, criterion2], ...)",
    description: "Sums cells that meet multiple criteria.",
    isModern: false,
    isVolatile: false,
    arguments: [
      { name: "sum_range", description: "The range to sum", required: true, type: "range" },
      { name: "criteria_range1", description: "First range to evaluate", required: true, type: "range" },
      { name: "criterion1", description: "First condition", required: true, type: "any" },
    ],
    examples: [
      {
        title: "Sum by single criterion",
        formula: '=SUMIFS(D:D, B:B, "North")',
        input: 'Sum amounts where Region="North"',
        output: 'Total for North region',
        explanation: "Sums column D where column B equals North.",
        level: "beginner",
      },
      {
        title: "Sum with multiple criteria",
        formula: '=SUMIFS(D:D, B:B, "North", C:C, "Active")',
        input: 'Region="North" AND Status="Active"',
        output: 'Filtered sum',
        explanation: "Multiple criteria work as AND. All must be true.",
        level: "intermediate",
      },
      {
        title: "Sum with comparison operators",
        formula: '=SUMIFS(D:D, D:D, ">1000", E:E, "<"&TODAY())',
        input: 'Amount>1000 AND Date<Today',
        output: 'Sum of past high-value transactions',
        explanation: "Use operators in quotes. Use & to concatenate with cell references.",
        level: "advanced",
      },
    ],
    pitfalls: [
      "All ranges must be same size",
      "Criteria order: range1, criterion1, range2, criterion2 (not grouped)",
      "Different from SUMIF - sum_range comes first",
      "Cannot use OR logic directly - need multiple SUMIFS added together",
    ],
    alternatives: ["SUMIF for single criterion", "FILTER + SUM", "Pivot table"],
    performanceNotes: "Efficient for multiple conditions. Faster than array formulas.",
  },
  // DATE & TIME
  {
    id: "eomonth",
    name: "EOMONTH",
    category: "date",
    syntax: "EOMONTH(start_date, months)",
    description: "Returns the last day of the month that is the indicated number of months before or after start_date.",
    isModern: false,
    isVolatile: false,
    arguments: [
      { name: "start_date", description: "The starting date", required: true, type: "date" },
      { name: "months", description: "Number of months before (negative) or after (positive) start_date", required: true, type: "number" },
    ],
    examples: [
      {
        title: "Get month end",
        formula: '=EOMONTH(A2, 0)',
        input: 'Any date in a month',
        output: 'Last day of that month',
        explanation: "Zero months means current month. Always returns last day.",
        level: "beginner",
      },
      {
        title: "Next month end",
        formula: '=EOMONTH(TODAY(), 1)',
        input: 'Today',
        output: 'Last day of next month',
        explanation: "Positive number moves forward. Useful for due dates.",
        level: "beginner",
      },
      {
        title: "Get month start",
        formula: '=EOMONTH(A2, -1) + 1',
        input: 'Date in current month',
        output: 'First day of current month',
        explanation: "Get previous month end, then add 1 day. Reliable month start.",
        level: "intermediate",
      },
    ],
    pitfalls: [
      "Returns a number - format as date",
      "Handles leap years automatically",
      "Invalid dates return #NUM!",
    ],
    alternatives: ["DATE function with day logic", "Power Query"],
    performanceNotes: "Fast and reliable. Much better than manual day calculations.",
  },
  {
    id: "networkdays",
    name: "NETWORKDAYS",
    category: "date",
    syntax: "NETWORKDAYS(start_date, end_date, [holidays])",
    description: "Returns the number of whole working days between two dates, excluding weekends and optional holidays.",
    isModern: false,
    isVolatile: false,
    arguments: [
      { name: "start_date", description: "Start date", required: true, type: "date" },
      { name: "end_date", description: "End date", required: true, type: "date" },
      { name: "holidays", description: "Range of dates to exclude", required: false, type: "range" },
    ],
    examples: [
      {
        title: "Business days between dates",
        formula: '=NETWORKDAYS(A2, B2)',
        input: 'Start and end date',
        output: 'Number of weekdays',
        explanation: "Automatically excludes Saturdays and Sundays.",
        level: "beginner",
      },
      {
        title: "Workdays excluding holidays",
        formula: '=NETWORKDAYS(A2, B2, Holidays!A:A)',
        input: 'Date range and holiday list',
        output: 'Working days minus holidays',
        explanation: "Reference a range containing holiday dates. Weekends and holidays excluded.",
        level: "intermediate",
      },
      {
        title: "Days until deadline",
        formula: '=NETWORKDAYS(TODAY(), A2, Holidays!A:A)',
        input: 'Deadline date',
        output: 'Business days remaining',
        explanation: "Useful for project management and deadline tracking.",
        level: "intermediate",
      },
    ],
    pitfalls: [
      "Saturday and Sunday hardcoded as weekend - use NETWORKDAYS.INTL for custom weekends",
      "Includes both start and end date",
      "Holiday range can be in any order",
    ],
    alternatives: ["NETWORKDAYS.INTL for custom weekends", "Manual calculation"],
    performanceNotes: "Efficient even with large date ranges and holiday lists.",
  },
  // LAMBDA FUNCTIONS
  {
    id: "let",
    name: "LET",
    category: "lambda",
    syntax: "LET(name1, value1, [name2, value2], ..., calculation)",
    description: "Assigns names to calculation results, allowing you to store intermediate values, values, and calculation results inside a formula.",
    isModern: true,
    isVolatile: false,
    arguments: [
      { name: "name1", description: "First variable name", required: true, type: "text" },
      { name: "value1", description: "Value to assign to name1", required: true, type: "any" },
      { name: "calculation", description: "Formula that uses the defined names", required: true, type: "formula" },
    ],
    examples: [
      {
        title: "Avoid repeating calculations",
        formula: '=LET(price, A2*B2, tax, price*0.1, price+tax)',
        input: 'Quantity * Unit price',
        output: 'Total with tax',
        explanation: "Calculate price once, then reuse it. More efficient and readable.",
        level: "intermediate",
      },
      {
        title: "Complex nested calculation",
        formula: '=LET(data, FILTER(A:D, B:B="Active"), sorted, SORT(data, 3, -1), TAKE(sorted, 10))',
        input: 'Multi-step data transformation',
        output: 'Top 10 active items',
        explanation: "Chain operations with clear names. Each step builds on previous.",
        level: "advanced",
      },
      {
        title: "Performance optimization",
        formula: '=LET(lookup, XLOOKUP(E2, A:A, B:D), INDEX(lookup, 1, MATCH(F2, B1:D1, 0)))',
        input: 'Reuse expensive lookup',
        output: 'Specific value from lookup result',
        explanation: "XLOOKUP executes once and result is reused. Much faster.",
        level: "advanced",
      },
    ],
    pitfalls: [
      "Only available in Excel 365",
      "Names are case-sensitive within the formula",
      "Variables only exist within the LET scope",
      "Last parameter must be the calculation expression",
    ],
    alternatives: ["Helper columns", "Repeating subformulas", "VBA"],
    performanceNotes: "Dramatically improves performance by eliminating redundant calculations. Makes complex formulas maintainable.",
  },
  
  // MORE LOOKUP & REFERENCE
  {
    id: "hlookup",
    name: "HLOOKUP",
    category: "lookup",
    syntax: "HLOOKUP(lookup_value, table_array, row_index_num, [range_lookup])",
    description: "Searches for a value in the top row of a table and returns a value in the same column from a specified row.",
    isModern: false,
    isVolatile: false,
    arguments: [
      { name: "lookup_value", description: "Value to search for in first row", required: true, type: "any" },
      { name: "table_array", description: "Table of information", required: true, type: "range" },
      { name: "row_index_num", description: "Row number to return value from", required: true, type: "number" },
      { name: "range_lookup", description: "TRUE=approximate, FALSE=exact", required: false, type: "boolean" },
    ],
    examples: [
      {
        title: "Basic horizontal lookup",
        formula: '=HLOOKUP("Sales", A1:D10, 3, FALSE)',
        input: 'Find "Sales" in row 1',
        output: 'Returns value from row 3',
        explanation: "Horizontal version of VLOOKUP. Searches left to right instead of top to bottom.",
        level: "beginner",
      },
      {
        title: "Approximate match",
        formula: '=HLOOKUP(A2, RateTable, 2, TRUE)',
        input: 'Find rate based on threshold',
        output: 'Closest rate',
        explanation: "Returns nearest match. First row must be sorted.",
        level: "intermediate",
      },
      {
        title: "Dynamic row selection",
        formula: '=HLOOKUP(B1, Data, MATCH(A2, A:A, 0), FALSE)',
        input: 'Variable row lookup',
        output: 'Dynamic result',
        explanation: "Combines with MATCH for flexible row selection.",
        level: "advanced",
      },
    ],
    pitfalls: ["First row must be sorted for approximate match", "Less common than VLOOKUP", "Consider XLOOKUP instead"],
    alternatives: ["XLOOKUP", "INDEX/MATCH"],
    performanceNotes: "XLOOKUP is more flexible and readable for new workbooks.",
  },

  {
    id: "choose",
    name: "CHOOSE",
    category: "lookup",
    syntax: "CHOOSE(index_num, value1, [value2], ...)",
    description: "Returns a value from a list of values based on a position number.",
    isModern: false,
    isVolatile: false,
    arguments: [
      { name: "index_num", description: "Position number (1-254)", required: true, type: "number" },
      { name: "value1", description: "First value option", required: true, type: "any" },
    ],
    examples: [
      {
        title: "Select from list",
        formula: '=CHOOSE(A2, "Red", "Green", "Blue")',
        input: '2',
        output: '"Green"',
        explanation: "Returns second value from the list.",
        level: "beginner",
      },
      {
        title: "Dynamic column reference",
        formula: '=SUM(CHOOSE(A1, B:B, C:C, D:D))',
        input: '1, 2, or 3',
        output: 'Sum of selected column',
        explanation: "Select which column to sum based on input.",
        level: "intermediate",
      },
      {
        title: "Array formula with CHOOSE",
        formula: '=CHOOSE({1,2,3}, "Q1", "Q2", "Q3")',
        input: 'Array constant',
        output: 'Array of quarters',
        explanation: "Generate arrays of values dynamically.",
        level: "advanced",
      },
    ],
    pitfalls: ["Index must be between 1 and number of values", "All values are evaluated even if not selected"],
    alternatives: ["SWITCH", "IFS", "Lookup tables"],
    performanceNotes: "Simple and fast but all values are calculated.",
  },

  {
    id: "offset",
    name: "OFFSET",
    category: "lookup",
    syntax: "OFFSET(reference, rows, cols, [height], [width])",
    description: "Returns a reference to a range that is a specified number of rows and columns from a cell or range of cells.",
    isModern: false,
    isVolatile: true,
    arguments: [
      { name: "reference", description: "Starting cell reference", required: true, type: "reference" },
      { name: "rows", description: "Number of rows to offset", required: true, type: "number" },
      { name: "cols", description: "Number of columns to offset", required: true, type: "number" },
      { name: "height", description: "Height of returned range", required: false, type: "number" },
      { name: "width", description: "Width of returned range", required: false, type: "number" },
    ],
    examples: [
      {
        title: "Simple offset",
        formula: '=OFFSET(A1, 2, 3)',
        input: 'Start at A1, move 2 down, 3 right',
        output: 'Reference to D3',
        explanation: "Returns the cell 2 rows down and 3 columns right from A1.",
        level: "beginner",
      },
      {
        title: "Dynamic range",
        formula: '=SUM(OFFSET(A1, 0, 0, COUNTA(A:A), 1))',
        input: 'Variable length column',
        output: 'Sum of all values',
        explanation: "Creates dynamic range that adjusts with data.",
        level: "intermediate",
      },
      {
        title: "Rolling average",
        formula: '=AVERAGE(OFFSET(A1, COUNT(A:A)-5, 0, 5, 1))',
        input: 'Last 5 entries',
        output: 'Moving average',
        explanation: "Calculates average of most recent 5 values.",
        level: "advanced",
      },
    ],
    pitfalls: ["VOLATILE - recalculates on every change", "Can slow down large workbooks", "Consider INDEX instead"],
    alternatives: ["INDEX with COUNTA", "Dynamic named ranges", "Modern dynamic arrays"],
    performanceNotes: "Avoid in large workbooks. Use INDEX or modern array functions instead.",
  },

  // MORE TEXT FUNCTIONS
  {
    id: "concatenate",
    name: "CONCATENATE / CONCAT",
    category: "text",
    syntax: "CONCAT(text1, [text2], ...)",
    description: "Joins multiple text strings into one string.",
    isModern: false,
    isVolatile: false,
    arguments: [
      { name: "text1", description: "First text to combine", required: true, type: "text" },
      { name: "text2", description: "Additional text", required: false, type: "text" },
    ],
    examples: [
      {
        title: "Simple concatenation",
        formula: '=CONCAT(A2, " ", B2)',
        input: '"John", "Smith"',
        output: '"John Smith"',
        explanation: "Joins first and last name with a space.",
        level: "beginner",
      },
      {
        title: "With delimiter",
        formula: '=CONCAT(A2, ", ", B2, ", ", C2)',
        input: 'Name, City, Country',
        output: 'Full address string',
        explanation: "Combine multiple cells with commas.",
        level: "beginner",
      },
      {
        title: "Formula with text",
        formula: '=CONCAT("Total: $", TEXT(SUM(A:A), "0.00"))',
        input: 'Sum of column A',
        output: '"Total: $1,234.56"',
        explanation: "Combine text with formatted numbers.",
        level: "intermediate",
      },
    ],
    pitfalls: ["CONCATENATE limited to 255 args", "Use & operator for simple cases", "TEXTJOIN better for ranges"],
    alternatives: ["& operator", "TEXTJOIN", "CONCAT (newer)"],
    performanceNotes: "& operator is faster for small concatenations.",
  },

  {
    id: "textjoin",
    name: "TEXTJOIN",
    category: "text",
    syntax: "TEXTJOIN(delimiter, ignore_empty, text1, [text2], ...)",
    description: "Joins multiple text strings with a delimiter and can ignore empty cells.",
    isModern: true,
    isVolatile: false,
    arguments: [
      { name: "delimiter", description: "Character(s) to insert between each text", required: true, type: "text" },
      { name: "ignore_empty", description: "TRUE to ignore empty cells", required: true, type: "boolean" },
      { name: "text1", description: "First text or range", required: true, type: "any" },
    ],
    examples: [
      {
        title: "Join with delimiter",
        formula: '=TEXTJOIN(", ", TRUE, A2:D2)',
        input: '"John", "", "Smith", "Jr"',
        output: '"John, Smith, Jr"',
        explanation: "Joins all values with comma, skipping empty cell.",
        level: "beginner",
      },
      {
        title: "Create list from column",
        formula: '=TEXTJOIN(CHAR(10), TRUE, A2:A100)',
        input: 'Column of names',
        output: 'Names on separate lines',
        explanation: "CHAR(10) is line break. Creates multiline text.",
        level: "intermediate",
      },
      {
        title: "Conditional join",
        formula: '=TEXTJOIN(", ", TRUE, IF(B2:B10>100, A2:A10, ""))',
        input: 'Names where value > 100',
        output: 'Filtered comma-separated list',
        explanation: "Combine TEXTJOIN with IF to filter.",
        level: "advanced",
      },
    ],
    pitfalls: ["Excel 365 and Excel 2019+ only", "Can create very long strings", "Performance with large ranges"],
    alternatives: ["CONCATENATE", "& operator", "Power Query"],
    performanceNotes: "Very powerful for creating CSV or delimited lists.",
  },

  {
    id: "proper",
    name: "PROPER",
    category: "text",
    syntax: "PROPER(text)",
    description: "Converts text to proper case (first letter of each word capitalized).",
    isModern: false,
    isVolatile: false,
    arguments: [
      { name: "text", description: "Text to convert", required: true, type: "text" },
    ],
    examples: [
      {
        title: "Basic proper case",
        formula: '=PROPER(A2)',
        input: '"john smith"',
        output: '"John Smith"',
        explanation: "Capitalizes first letter of each word.",
        level: "beginner",
      },
      {
        title: "Fix all caps",
        formula: '=PROPER(LOWER(A2))',
        input: '"JOHN SMITH"',
        output: '"John Smith"',
        explanation: "Convert to lowercase first, then proper case.",
        level: "beginner",
      },
      {
        title: "Names with apostrophes",
        formula: '=PROPER(A2)',
        input: '"o\'brien"',
        output: '"O\'Brien"',
        explanation: "Handles apostrophes correctly.",
        level: "intermediate",
      },
    ],
    pitfalls: ["Can incorrectly capitalize words like 'McDonald'", "Numbers reset capitalization", "Doesn't handle Roman numerals"],
    alternatives: ["UPPER", "LOWER", "Manual formatting"],
    performanceNotes: "Fast function. Useful for cleaning imported data.",
  },

  // MORE MATH FUNCTIONS
  {
    id: "round",
    name: "ROUND",
    category: "math",
    syntax: "ROUND(number, num_digits)",
    description: "Rounds a number to a specified number of digits.",
    isModern: false,
    isVolatile: false,
    arguments: [
      { name: "number", description: "Number to round", required: true, type: "number" },
      { name: "num_digits", description: "Number of decimal places", required: true, type: "number" },
    ],
    examples: [
      {
        title: "Round to 2 decimals",
        formula: '=ROUND(A2, 2)',
        input: '3.14159',
        output: '3.14',
        explanation: "Standard rounding to 2 decimal places.",
        level: "beginner",
      },
      {
        title: "Round to nearest 10",
        formula: '=ROUND(A2, -1)',
        input: '1234',
        output: '1230',
        explanation: "Negative digits round to left of decimal (tens, hundreds, etc).",
        level: "intermediate",
      },
      {
        title: "Round to nearest 5",
        formula: '=ROUND(A2/5, 0)*5',
        input: '23',
        output: '25',
        explanation: "Divide by 5, round, multiply by 5. Works for any increment.",
        level: "advanced",
      },
    ],
    pitfalls: ["Banker's rounding (0.5 rounds to nearest even)", "Different from display formatting", "Can accumulate errors"],
    alternatives: ["ROUNDUP", "ROUNDDOWN", "MROUND", "INT", "TRUNC"],
    performanceNotes: "Fast and commonly used. Use MROUND for specific increments.",
  },

  {
    id: "rand-randbetween",
    name: "RAND / RANDBETWEEN",
    category: "math",
    syntax: "RANDBETWEEN(bottom, top)",
    description: "Returns a random integer between two numbers.",
    isModern: false,
    isVolatile: true,
    arguments: [
      { name: "bottom", description: "Smallest integer to return", required: true, type: "number" },
      { name: "top", description: "Largest integer to return", required: true, type: "number" },
    ],
    examples: [
      {
        title: "Random number 1-100",
        formula: '=RANDBETWEEN(1, 100)',
        input: 'No input',
        output: 'Random integer 1-100',
        explanation: "Generates random integer in range.",
        level: "beginner",
      },
      {
        title: "Random date this year",
        formula: '=DATE(2025, RANDBETWEEN(1,12), RANDBETWEEN(1,28))',
        input: 'No input',
        output: 'Random date',
        explanation: "Create random dates by randomizing month and day.",
        level: "intermediate",
      },
      {
        title: "Random sample",
        formula: '=INDEX(A2:A100, RANDBETWEEN(1, COUNTA(A2:A100)))',
        input: 'List of items',
        output: 'Random item from list',
        explanation: "Select random value from range.",
        level: "advanced",
      },
    ],
    pitfalls: ["VOLATILE - recalculates constantly", "Changes every time sheet calculates", "Use F9 to freeze values"],
    alternatives: ["RAND() for decimals", "Copy/Paste Values to freeze", "VBA for stable random"],
    performanceNotes: "Avoid in large datasets. Copy values when done.",
  },

  {
    id: "aggregate",
    name: "AGGREGATE",
    category: "math",
    syntax: "AGGREGATE(function_num, options, array, [k])",
    description: "Returns an aggregate calculation (like SUM, AVERAGE) while ignoring errors, hidden rows, or nested subtotals.",
    isModern: false,
    isVolatile: false,
    arguments: [
      { name: "function_num", description: "1-19: function to perform (1=AVERAGE, 9=SUM, etc)", required: true, type: "number" },
      { name: "options", description: "0-7: what to ignore (errors, hidden, nested)", required: true, type: "number" },
      { name: "array", description: "Range to calculate", required: true, type: "range" },
    ],
    examples: [
      {
        title: "Sum ignoring errors",
        formula: '=AGGREGATE(9, 6, A2:A100)',
        input: 'Range with #DIV/0! errors',
        output: 'Sum of valid numbers',
        explanation: "Function 9=SUM, option 6=ignore errors.",
        level: "intermediate",
      },
      {
        title: "Average visible cells",
        formula: '=AGGREGATE(1, 5, A2:A100)',
        input: 'Filtered range',
        output: 'Average of visible cells only',
        explanation: "Function 1=AVERAGE, option 5=ignore hidden.",
        level: "intermediate",
      },
      {
        title: "Large value ignoring errors",
        formula: '=AGGREGATE(14, 6, A2:A100, 3)',
        input: 'Range with errors',
        output: '3rd largest value',
        explanation: "Function 14=LARGE, k=3 for 3rd largest.",
        level: "advanced",
      },
    ],
    pitfalls: ["18 different function numbers to remember", "Options parameter not intuitive", "Complex syntax"],
    alternatives: ["SUMIF with criteria", "Array formulas", "Manual filtering"],
    performanceNotes: "Very powerful for filtered or error-prone data.",
  },

  // MORE DATE FUNCTIONS
  {
    id: "today-now",
    name: "TODAY / NOW",
    category: "date",
    syntax: "TODAY() or NOW()",
    description: "Returns the current date (TODAY) or current date and time (NOW).",
    isModern: false,
    isVolatile: true,
    arguments: [],
    examples: [
      {
        title: "Current date",
        formula: '=TODAY()',
        input: 'No input',
        output: '11/8/2025',
        explanation: "Returns today's date. Updates automatically.",
        level: "beginner",
      },
      {
        title: "Days until deadline",
        formula: '=A2-TODAY()',
        input: 'Future date in A2',
        output: 'Days remaining',
        explanation: "Calculate days between today and future date.",
        level: "beginner",
      },
      {
        title: "Age calculator",
        formula: '=DATEDIF(A2, TODAY(), "Y")',
        input: 'Birth date in A2',
        output: 'Age in years',
        explanation: "Calculate age from birth date to today.",
        level: "intermediate",
      },
    ],
    pitfalls: ["VOLATILE - updates on every calculation", "NOW includes time which can affect comparisons", "Use static dates for historical data"],
    alternatives: ["Manual date entry", "Ctrl+; shortcut", "Date formula"],
    performanceNotes: "Recalculates constantly. Use Ctrl+; for static dates.",
  },

  {
    id: "edate",
    name: "EDATE",
    category: "date",
    syntax: "EDATE(start_date, months)",
    description: "Returns a date that is a specified number of months before or after a date.",
    isModern: false,
    isVolatile: false,
    arguments: [
      { name: "start_date", description: "Starting date", required: true, type: "date" },
      { name: "months", description: "Number of months (positive=future, negative=past)", required: true, type: "number" },
    ],
    examples: [
      {
        title: "3 months from date",
        formula: '=EDATE(A2, 3)',
        input: '1/1/2025',
        output: '4/1/2025',
        explanation: "Adds 3 months to the date.",
        level: "beginner",
      },
      {
        title: "Contract renewal date",
        formula: '=EDATE(A2, 12)',
        input: 'Contract start date',
        output: 'Date one year later',
        explanation: "Calculate annual renewal dates.",
        level: "beginner",
      },
      {
        title: "Quarterly dates",
        formula: '=EDATE($A$2, (ROW()-1)*3)',
        input: 'Starting date in A2',
        output: 'Series of quarterly dates',
        explanation: "Drag down to create quarterly date series.",
        level: "intermediate",
      },
    ],
    pitfalls: ["Returns same day of month (31st may become 30th)", "Time component is lost", "Different from adding days"],
    alternatives: ["DATE function with month math", "EOMONTH + 1"],
    performanceNotes: "Fast and reliable for month-based calculations.",
  },

  {
    id: "yearfrac",
    name: "YEARFRAC",
    category: "date",
    syntax: "YEARFRAC(start_date, end_date, [basis])",
    description: "Calculates the fraction of the year between two dates.",
    isModern: false,
    isVolatile: false,
    arguments: [
      { name: "start_date", description: "Start of period", required: true, type: "date" },
      { name: "end_date", description: "End of period", required: true, type: "date" },
      { name: "basis", description: "Day count basis (0-4)", required: false, type: "number" },
    ],
    examples: [
      {
        title: "Fraction of year",
        formula: '=YEARFRAC(A2, B2)',
        input: '1/1/2025 to 7/1/2025',
        output: '0.5 (half year)',
        explanation: "Calculate portion of year between dates.",
        level: "beginner",
      },
      {
        title: "Pro-rated salary",
        formula: '=C2 * YEARFRAC(A2, B2)',
        input: 'Annual salary × fraction',
        output: 'Pro-rated amount',
        explanation: "Calculate partial year salary.",
        level: "intermediate",
      },
      {
        title: "Age with decimals",
        formula: '=YEARFRAC(A2, TODAY())',
        input: 'Birth date',
        output: 'Exact age (e.g., 25.7 years)',
        explanation: "Precise age calculation including partial years.",
        level: "intermediate",
      },
    ],
    pitfalls: ["Different basis methods give different results", "Financial calculations need correct basis", "May not match DATEDIF"],
    alternatives: ["DATEDIF", "Manual date arithmetic", "Days/365"],
    performanceNotes: "Essential for financial calculations and pro-rating.",
  },

  // MORE LOGICAL FUNCTIONS
  {
    id: "and-or",
    name: "AND / OR",
    category: "logical",
    syntax: "AND(logical1, [logical2], ...) or OR(logical1, [logical2], ...)",
    description: "Tests multiple conditions. AND returns TRUE if all are TRUE. OR returns TRUE if any are TRUE.",
    isModern: false,
    isVolatile: false,
    arguments: [
      { name: "logical1", description: "First condition to test", required: true, type: "boolean" },
      { name: "logical2", description: "Additional conditions", required: false, type: "boolean" },
    ],
    examples: [
      {
        title: "Multiple conditions (AND)",
        formula: '=AND(A2>100, B2="Active")',
        input: 'Amount > 100 AND Status = Active',
        output: 'TRUE or FALSE',
        explanation: "Both conditions must be true.",
        level: "beginner",
      },
      {
        title: "Either condition (OR)",
        formula: '=OR(A2>1000, B2="VIP")',
        input: 'Amount > 1000 OR Status = VIP',
        output: 'TRUE or FALSE',
        explanation: "At least one condition must be true.",
        level: "beginner",
      },
      {
        title: "Complex nested logic",
        formula: '=IF(AND(OR(A2="A", A2="B"), C2>100), "Approved", "Denied")',
        input: 'Grade A or B, AND Score > 100',
        output: '"Approved" or "Denied"',
        explanation: "Combine AND/OR for complex decision trees.",
        level: "advanced",
      },
    ],
    pitfalls: ["Can only handle up to 255 conditions", "Short-circuit evaluation not supported", "Use * for AND and + for OR in array formulas"],
    alternatives: ["Multiple nested IFs", "Array multiplication/addition", "IFS for simpler logic"],
    performanceNotes: "Simple and fast. Use array operators (*,+) for better performance in arrays.",
  },

  {
    id: "iferror",
    name: "IFERROR",
    category: "logical",
    syntax: "IFERROR(value, value_if_error)",
    description: "Returns a value if the formula evaluates to an error; otherwise returns the result of the formula.",
    isModern: false,
    isVolatile: false,
    arguments: [
      { name: "value", description: "Formula or value to check", required: true, type: "any" },
      { name: "value_if_error", description: "Value to return if error", required: true, type: "any" },
    ],
    examples: [
      {
        title: "Handle division by zero",
        formula: '=IFERROR(A2/B2, 0)',
        input: 'Division that might fail',
        output: '0 instead of #DIV/0!',
        explanation: "Returns 0 if division fails.",
        level: "beginner",
      },
      {
        title: "Lookup with fallback",
        formula: '=IFERROR(VLOOKUP(A2, Table, 2, FALSE), "Not Found")',
        input: 'Lookup that might not match',
        output: '"Not Found" instead of #N/A',
        explanation: "Graceful error handling for lookups.",
        level: "intermediate",
      },
      {
        title: "Clean data extraction",
        formula: '=IFERROR(VALUE(A2), A2)',
        input: 'Mixed text and numbers',
        output: 'Number if possible, text otherwise',
        explanation: "Try to convert to number, keep text if fails.",
        level: "intermediate",
      },
    ],
    pitfalls: ["Hides all errors including formula mistakes", "Can mask data quality issues", "Consider IFNA for specific #N/A handling"],
    alternatives: ["IFNA", "IF with ISERROR", "Error checking functions"],
    performanceNotes: "Very useful but don't overuse. Fix root cause of errors when possible.",
  },

  {
    id: "isblank-isnumber",
    name: "ISBLANK / ISNUMBER / ISTEXT",
    category: "logical",
    syntax: "ISBLANK(value) or ISNUMBER(value) or ISTEXT(value)",
    description: "Tests the type of value. ISBLANK checks if empty, ISNUMBER checks if numeric, ISTEXT checks if text.",
    isModern: false,
    isVolatile: false,
    arguments: [
      { name: "value", description: "Value or cell to test", required: true, type: "any" },
    ],
    examples: [
      {
        title: "Check if blank",
        formula: '=IF(ISBLANK(A2), "Empty", "Has Data")',
        input: 'Empty cell or cell with data',
        output: '"Empty" or "Has Data"',
        explanation: "Detect empty cells.",
        level: "beginner",
      },
      {
        title: "Validate data type",
        formula: '=IF(ISNUMBER(A2), "Number", "Text")',
        input: 'Any cell value',
        output: '"Number" or "Text"',
        explanation: "Check if cell contains number.",
        level: "beginner",
      },
      {
        title: "Conditional calculation",
        formula: '=IF(ISNUMBER(A2), A2*1.1, A2)',
        input: 'Mixed data types',
        output: 'Numbers increased 10%, text unchanged',
        explanation: "Only process numeric values.",
        level: "intermediate",
      },
    ],
    pitfalls: ["Formulas returning \"\" are not blank", "ISBLANK only TRUE for truly empty cells", "Space character is not blank"],
    alternatives: ["ISNA", "ISERROR", "TYPE function", "Direct comparison"],
    performanceNotes: "Fast validation functions. Useful for data cleaning.",
  },

  // MORE DYNAMIC ARRAY FUNCTIONS
  {
    id: "take-drop",
    name: "TAKE / DROP",
    category: "dynamic-array",
    syntax: "TAKE(array, rows, [columns]) or DROP(array, rows, [columns])",
    description: "TAKE returns first/last n rows or columns. DROP removes first/last n rows or columns.",
    isModern: true,
    isVolatile: false,
    arguments: [
      { name: "array", description: "Array or range", required: true, type: "range" },
      { name: "rows", description: "Number of rows (negative for last rows)", required: true, type: "number" },
      { name: "columns", description: "Number of columns", required: false, type: "number" },
    ],
    examples: [
      {
        title: "Take first 5 rows",
        formula: '=TAKE(A1:D100, 5)',
        input: 'Large dataset',
        output: 'First 5 rows',
        explanation: "Extract top 5 rows from data.",
        level: "beginner",
      },
      {
        title: "Take last 10 rows",
        formula: '=TAKE(A1:D100, -10)',
        input: 'Large dataset',
        output: 'Last 10 rows',
        explanation: "Negative number takes from the end.",
        level: "beginner",
      },
      {
        title: "Drop header row",
        formula: '=DROP(A1:D100, 1)',
        input: 'Data with header',
        output: 'Data without header',
        explanation: "Remove first row (header) from range.",
        level: "intermediate",
      },
    ],
    pitfalls: ["Excel 365 only", "Returns #CALC! if rows exceed range size", "Negative values work differently"],
    alternatives: ["INDEX with ROW", "OFFSET", "Manual range selection"],
    performanceNotes: "Very clean and efficient for extracting portions of data.",
  },

  {
    id: "sequence",
    name: "SEQUENCE",
    category: "dynamic-array",
    syntax: "SEQUENCE(rows, [columns], [start], [step])",
    description: "Generates an array of sequential numbers.",
    isModern: true,
    isVolatile: false,
    arguments: [
      { name: "rows", description: "Number of rows to return", required: true, type: "number" },
      { name: "columns", description: "Number of columns to return", required: false, type: "number" },
      { name: "start", description: "First number in sequence", required: false, type: "number" },
      { name: "step", description: "Amount to increment", required: false, type: "number" },
    ],
    examples: [
      {
        title: "Simple sequence 1-10",
        formula: '=SEQUENCE(10)',
        input: 'No input',
        output: 'Numbers 1 through 10',
        explanation: "Generate sequential numbers.",
        level: "beginner",
      },
      {
        title: "Even numbers",
        formula: '=SEQUENCE(10, 1, 2, 2)',
        input: 'Start at 2, step by 2',
        output: '2, 4, 6, 8...20',
        explanation: "Create series of even numbers.",
        level: "intermediate",
      },
      {
        title: "Date series",
        formula: '=TODAY() + SEQUENCE(7) - 1',
        input: 'Today as starting point',
        output: 'Next 7 days',
        explanation: "Combine with TODAY() to create date series.",
        level: "advanced",
      },
    ],
    pitfalls: ["Excel 365 only", "Large sequences use memory", "Spills into adjacent cells"],
    alternatives: ["Fill handle", "ROW function", "Manual entry"],
    performanceNotes: "Excellent for creating test data and date ranges.",
  },

  {
    id: "sortby",
    name: "SORTBY",
    category: "dynamic-array",
    syntax: "SORTBY(array, by_array1, [sort_order1], [by_array2], [sort_order2], ...)",
    description: "Sorts an array based on the values in a corresponding range or array.",
    isModern: true,
    isVolatile: false,
    arguments: [
      { name: "array", description: "Range to sort", required: true, type: "range" },
      { name: "by_array1", description: "Range to sort by", required: true, type: "range" },
      { name: "sort_order1", description: "1=ascending, -1=descending", required: false, type: "number" },
    ],
    examples: [
      {
        title: "Sort by another column",
        formula: '=SORTBY(A2:C100, B2:B100, -1)',
        input: 'Data in A:C, sort by B descending',
        output: 'All data sorted by column B',
        explanation: "Sort entire table by specific column.",
        level: "beginner",
      },
      {
        title: "Multi-level sort",
        formula: '=SORTBY(A2:D100, B2:B100, 1, C2:C100, -1)',
        input: 'Sort by Region then Amount',
        output: 'Sorted by Region A-Z, then Amount high-low',
        explanation: "Primary and secondary sort.",
        level: "intermediate",
      },
      {
        title: "Sort by calculated value",
        formula: '=SORTBY(A2:C100, B2:B100*C2:C100, -1)',
        input: 'Sort by Qty × Price',
        output: 'Sorted by total value',
        explanation: "Sort by formula result without helper column.",
        level: "advanced",
      },
    ],
    pitfalls: ["Excel 365 only", "by_array must be same size as array rows", "Multiple sort orders can be confusing"],
    alternatives: ["SORT function", "Manual sorting", "Power Query"],
    performanceNotes: "More flexible than SORT. Great for complex sorting.",
  },

  // MORE STATISTICAL FUNCTIONS
  {
    id: "countif-countifs",
    name: "COUNTIF / COUNTIFS",
    category: "math",
    syntax: "COUNTIFS(criteria_range1, criterion1, [criteria_range2, criterion2], ...)",
    description: "Counts cells that meet multiple criteria.",
    isModern: false,
    isVolatile: false,
    arguments: [
      { name: "criteria_range1", description: "First range to evaluate", required: true, type: "range" },
      { name: "criterion1", description: "First condition", required: true, type: "any" },
    ],
    examples: [
      {
        title: "Count matching values",
        formula: '=COUNTIF(A2:A100, "Active")',
        input: 'Range with statuses',
        output: 'Number of "Active" items',
        explanation: "Count cells that equal specific value.",
        level: "beginner",
      },
      {
        title: "Count with multiple criteria",
        formula: '=COUNTIFS(A2:A100, "Active", B2:B100, ">1000")',
        input: 'Active items with amount > 1000',
        output: 'Count meeting both conditions',
        explanation: "Multiple criteria work as AND.",
        level: "intermediate",
      },
      {
        title: "Count cells not blank",
        formula: '=COUNTIF(A2:A100, "<>")',
        input: 'Range with some blanks',
        output: 'Number of non-blank cells',
        explanation: '"<>" means not equal to empty.',
        level: "intermediate",
      },
    ],
    pitfalls: ["Wildcard * and ? work in criteria", "Dates need proper formatting", "Case-insensitive matching"],
    alternatives: ["SUMPRODUCT", "Array formulas", "Pivot tables"],
    performanceNotes: "Fast and reliable for counting with conditions.",
  },

  {
    id: "averageif-averageifs",
    name: "AVERAGEIF / AVERAGEIFS",
    category: "math",
    syntax: "AVERAGEIFS(average_range, criteria_range1, criterion1, [criteria_range2, criterion2], ...)",
    description: "Calculates average of cells that meet multiple criteria.",
    isModern: false,
    isVolatile: false,
    arguments: [
      { name: "average_range", description: "Range to average", required: true, type: "range" },
      { name: "criteria_range1", description: "First range to evaluate", required: true, type: "range" },
      { name: "criterion1", description: "First condition", required: true, type: "any" },
    ],
    examples: [
      {
        title: "Average by category",
        formula: '=AVERAGEIF(B2:B100, "North", C2:C100)',
        input: 'Average sales for North region',
        output: 'Average of matching values',
        explanation: "Average C where B equals North.",
        level: "beginner",
      },
      {
        title: "Average with multiple criteria",
        formula: '=AVERAGEIFS(D2:D100, B2:B100, "North", C2:C100, "Active")',
        input: 'North region AND Active status',
        output: 'Filtered average',
        explanation: "Both conditions must be true.",
        level: "intermediate",
      },
      {
        title: "Average excluding outliers",
        formula: '=AVERAGEIFS(A2:A100, A2:A100, ">"&PERCENTILE(A2:A100,0.1), A2:A100, "<"&PERCENTILE(A2:A100,0.9))',
        input: 'Remove top and bottom 10%',
        output: 'Trimmed average',
        explanation: "Average only middle 80% of data.",
        level: "advanced",
      },
    ],
    pitfalls: ["All ranges must be same size", "Order different from AVERAGEIF", "Ignores text and empty cells"],
    alternatives: ["AVERAGE with IF array", "Pivot tables", "FILTER + AVERAGE"],
    performanceNotes: "Essential for conditional averages.",
  },

  // FINANCIAL FUNCTIONS
  {
    id: "pmt",
    name: "PMT",
    category: "financial",
    syntax: "PMT(rate, nper, pv, [fv], [type])",
    description: "Calculates the periodic payment for a loan based on constant payments and a constant interest rate.",
    isModern: false,
    isVolatile: false,
    arguments: [
      { name: "rate", description: "Interest rate per period", required: true, type: "number" },
      { name: "nper", description: "Total number of payment periods", required: true, type: "number" },
      { name: "pv", description: "Present value (loan amount)", required: true, type: "number" },
      { name: "fv", description: "Future value (default 0)", required: false, type: "number" },
      { name: "type", description: "0=end of period, 1=beginning", required: false, type: "number" },
    ],
    examples: [
      {
        title: "Monthly loan payment",
        formula: '=PMT(5%/12, 360, 200000)',
        input: '5% annual rate, 30 years, $200k loan',
        output: '-$1,073.64 per month',
        explanation: "Negative because it's money going out.",
        level: "beginner",
      },
      {
        title: "Car payment",
        formula: '=PMT(6.5%/12, 60, 25000)',
        input: '6.5% APR, 5 years, $25k car',
        output: 'Monthly payment',
        explanation: "Divide annual rate by 12 for monthly rate.",
        level: "beginner",
      },
      {
        title: "Payment with balloon",
        formula: '=PMT(4%/12, 36, 10000, -2000, 0)',
        input: '$10k loan, $2k balloon payment',
        output: 'Lower monthly payment',
        explanation: "Negative fv means money owed at end.",
        level: "advanced",
      },
    ],
    pitfalls: ["Rate must match period (annual rate/12 for monthly)", "Result is negative (cash outflow)", "Assumes constant rate"],
    alternatives: ["Online calculators", "IPMT for interest portion", "PPMT for principal"],
    performanceNotes: "Essential for loan and mortgage calculations.",
  },

  {
    id: "npv-irr",
    name: "NPV / IRR",
    category: "financial",
    syntax: "NPV(rate, value1, [value2], ...) or IRR(values, [guess])",
    description: "NPV calculates net present value. IRR calculates internal rate of return.",
    isModern: false,
    isVolatile: false,
    arguments: [
      { name: "rate", description: "Discount rate per period", required: true, type: "number" },
      { name: "value1", description: "First cash flow", required: true, type: "number" },
    ],
    examples: [
      {
        title: "Project NPV",
        formula: '=NPV(10%, B2:B6) + A2',
        input: 'Initial investment + future cash flows',
        output: 'Net present value',
        explanation: "Add initial investment separately (period 0).",
        level: "intermediate",
      },
      {
        title: "Investment IRR",
        formula: '=IRR(A2:A6)',
        input: 'Series of cash flows',
        output: 'Return rate as decimal',
        explanation: "First value should be negative (investment).",
        level: "intermediate",
      },
      {
        title: "Quarterly NPV",
        formula: '=NPV(10%/4, B2:B21)',
        input: 'Quarterly discount rate',
        output: 'NPV for quarterly periods',
        explanation: "Adjust rate to match period frequency.",
        level: "advanced",
      },
    ],
    pitfalls: ["NPV assumes first cash flow is period 1, not 0", "IRR needs at least one positive and one negative value", "IRR may have multiple solutions"],
    alternatives: ["XNPV for irregular periods", "XIRR for irregular periods"],
    performanceNotes: "Standard for investment analysis and capital budgeting.",
  },

  // INFORMATION FUNCTIONS
  {
    id: "cell-info",
    name: "CELL",
    category: "information",
    syntax: "CELL(info_type, [reference])",
    description: "Returns information about the formatting, location, or contents of a cell.",
    isModern: false,
    isVolatile: true,
    arguments: [
      { name: "info_type", description: "Type of information (address, color, contents, etc)", required: true, type: "text" },
      { name: "reference", description: "Cell to analyze", required: false, type: "reference" },
    ],
    examples: [
      {
        title: "Get cell address",
        formula: '=CELL("address", A1)',
        input: 'Reference to A1',
        output: '"$A$1"',
        explanation: "Returns absolute address of cell.",
        level: "beginner",
      },
      {
        title: "Check cell format",
        formula: '=CELL("format", A2)',
        input: 'Formatted cell',
        output: 'Format code',
        explanation: "Returns number format applied.",
        level: "intermediate",
      },
      {
        title: "Get file path",
        formula: '=CELL("filename")',
        input: 'No reference needed',
        output: 'Full file path',
        explanation: "Returns workbook path and name.",
        level: "intermediate",
      },
    ],
    pitfalls: ["VOLATILE - recalculates constantly", "Some info types don't work in all contexts", "Returns different values in different Excel versions"],
    alternatives: ["FORMULATEXT", "ISFORMULA", "Direct cell references"],
    performanceNotes: "Useful for debugging but avoid in large workbooks.",
  },

  {
    id: "type",
    name: "TYPE",
    category: "information",
    syntax: "TYPE(value)",
    description: "Returns a number indicating the data type of a value.",
    isModern: false,
    isVolatile: false,
    arguments: [
      { name: "value", description: "Value to test", required: true, type: "any" },
    ],
    examples: [
      {
        title: "Check data type",
        formula: '=TYPE(A2)',
        input: 'Any cell',
        output: '1=number, 2=text, 4=logical, 16=error, 64=array',
        explanation: "Returns numeric code for data type.",
        level: "beginner",
      },
      {
        title: "Conditional processing",
        formula: '=IF(TYPE(A2)=1, A2*2, A2)',
        input: 'Mixed data',
        output: 'Double numbers, leave text unchanged',
        explanation: "Process only if number (type 1).",
        level: "intermediate",
      },
      {
        title: "Error detection",
        formula: '=TYPE(A2)=16',
        input: 'Cell that might have error',
        output: 'TRUE if error, FALSE otherwise',
        explanation: "Type 16 indicates error value.",
        level: "intermediate",
      },
    ],
    pitfalls: ["Returns different codes for different types", "Doesn't distinguish between date and number", "Array = 64 only in certain contexts"],
    alternatives: ["ISBLANK", "ISNUMBER", "ISTEXT", "ISERROR"],
    performanceNotes: "Fast type checking for data validation.",
  },

  {
    id: "na",
    name: "NA",
    category: "information",
    syntax: "NA()",
    description: "Returns the #N/A error value. Useful for marking cells as 'not applicable'.",
    isModern: false,
    isVolatile: false,
    arguments: [],
    examples: [
      {
        title: "Mark as not applicable",
        formula: '=IF(A2="", NA(), B2/A2)',
        input: 'Division with potential blank',
        output: '#N/A if blank, result otherwise',
        explanation: "Use #N/A to indicate missing data.",
        level: "beginner",
      },
      {
        title: "Chart gaps",
        formula: '=IF(A2=0, NA(), A2)',
        input: 'Data with zeros',
        output: 'Zeros become #N/A',
        explanation: "Charts skip #N/A, creating gaps instead of zero lines.",
        level: "intermediate",
      },
      {
        title: "Force error",
        formula: '=IF(B2<C2, NA(), "Valid")',
        input: 'Data validation',
        output: '#N/A if invalid',
        explanation: "Use to signal validation failures.",
        level: "intermediate",
      },
    ],
    pitfalls: ["#N/A propagates through formulas", "Different from 0 or blank", "Use IFNA to handle #N/A errors"],
    alternatives: ["Empty string", "Zero", "Text message"],
    performanceNotes: "Standard way to indicate missing or not applicable data.",
  },
];

// Formula categories for filtering
export const FORMULA_CATEGORIES = [
  { id: "all", name: "All Formulas", count: FORMULAS.length },
  { id: "lookup", name: "Lookup & Reference", count: FORMULAS.filter(f => f.category === "lookup").length },
  { id: "text", name: "Text Functions", count: FORMULAS.filter(f => f.category === "text").length },
  { id: "dynamic-array", name: "Dynamic Arrays", count: FORMULAS.filter(f => f.category === "dynamic-array").length },
  { id: "logical", name: "Logical", count: FORMULAS.filter(f => f.category === "logical").length },
  { id: "math", name: "Math & Stats", count: FORMULAS.filter(f => f.category === "math").length },
  { id: "date", name: "Date & Time", count: FORMULAS.filter(f => f.category === "date").length },
  { id: "financial", name: "Financial", count: FORMULAS.filter(f => f.category === "financial").length },
  { id: "information", name: "Information", count: FORMULAS.filter(f => f.category === "information").length },
  { id: "lambda", name: "Lambda & Advanced", count: FORMULAS.filter(f => f.category === "lambda").length },
];

